// Mocks generated by Mockito 5.4.4 from annotations
// in transactions_mobile/test/update_prompt_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:transactions_mobile/models/transaction.dart' as _i2;
import 'package:transactions_mobile/models/update_metadata.dart' as _i3;
import 'package:transactions_mobile/services/api_client.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTransaction_0 extends _i1.SmartFake implements _i2.Transaction {
  _FakeTransaction_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUpdateMetadata_1 extends _i1.SmartFake
    implements _i3.UpdateMetadata {
  _FakeUpdateMetadata_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i4.ApiClient {
  @override
  _i5.Future<List<_i2.Transaction>> getTransactions({
    int? limit = 50,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTransactions,
          [],
          {
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue:
            _i5.Future<List<_i2.Transaction>>.value(<_i2.Transaction>[]),
        returnValueForMissingStub:
            _i5.Future<List<_i2.Transaction>>.value(<_i2.Transaction>[]),
      ) as _i5.Future<List<_i2.Transaction>>);

  @override
  _i5.Future<_i2.Transaction> getTransactionById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTransactionById,
          [id],
        ),
        returnValue: _i5.Future<_i2.Transaction>.value(_FakeTransaction_0(
          this,
          Invocation.method(
            #getTransactionById,
            [id],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.Transaction>.value(_FakeTransaction_0(
          this,
          Invocation.method(
            #getTransactionById,
            [id],
          ),
        )),
      ) as _i5.Future<_i2.Transaction>);

  @override
  _i5.Future<_i2.Transaction> createTransaction(
          Map<String, dynamic>? payload) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTransaction,
          [payload],
        ),
        returnValue: _i5.Future<_i2.Transaction>.value(_FakeTransaction_0(
          this,
          Invocation.method(
            #createTransaction,
            [payload],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.Transaction>.value(_FakeTransaction_0(
          this,
          Invocation.method(
            #createTransaction,
            [payload],
          ),
        )),
      ) as _i5.Future<_i2.Transaction>);

  @override
  _i5.Future<_i2.Transaction> updateTransaction(
    String? id,
    Map<String, dynamic>? payload,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTransaction,
          [
            id,
            payload,
          ],
        ),
        returnValue: _i5.Future<_i2.Transaction>.value(_FakeTransaction_0(
          this,
          Invocation.method(
            #updateTransaction,
            [
              id,
              payload,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.Transaction>.value(_FakeTransaction_0(
          this,
          Invocation.method(
            #updateTransaction,
            [
              id,
              payload,
            ],
          ),
        )),
      ) as _i5.Future<_i2.Transaction>);

  @override
  _i5.Future<void> reviewTransaction(
    String? id,
    Map<String, dynamic>? payload,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #reviewTransaction,
          [
            id,
            payload,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> exportTransactions(String? savePath) => (super.noSuchMethod(
        Invocation.method(
          #exportTransactions,
          [savePath],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.UpdateMetadata> fetchLatestAppVersion() => (super.noSuchMethod(
        Invocation.method(
          #fetchLatestAppVersion,
          [],
        ),
        returnValue: _i5.Future<_i3.UpdateMetadata>.value(_FakeUpdateMetadata_1(
          this,
          Invocation.method(
            #fetchLatestAppVersion,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.UpdateMetadata>.value(_FakeUpdateMetadata_1(
          this,
          Invocation.method(
            #fetchLatestAppVersion,
            [],
          ),
        )),
      ) as _i5.Future<_i3.UpdateMetadata>);
}
