"""Add processing state fields to raw_messages

Revision ID: 079341ba1d7d
Revises: 327c9c632d86
Create Date: 2026-03-15 19:31:07.838690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '079341ba1d7d'
down_revision: Union[str, Sequence[str], None] = '327c9c632d86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_messages', sa.Column('processing_status', sa.String(length=50), server_default='pending', nullable=False))
    op.add_column('raw_messages', sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('raw_messages', sa.Column('processing_completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_messages', 'processing_completed_at')
    op.drop_column('raw_messages', 'processing_started_at')
    op.drop_column('raw_messages', 'processing_status')
    # ### end Alembic commands ###
