"""add meta routing fields to raw messages

Revision ID: 2eae650197ca
Revises: d7de164620a1
Create Date: 2026-06-15 16:04:10.302854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2eae650197ca'
down_revision: Union[str, Sequence[str], None] = 'd7de164620a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.add_column('audit_logs', sa.Column('business_id', sa.String(length=255), nullable=True))
    op.add_column('audit_logs', sa.Column('actor_user_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_business_id'), 'audit_logs', ['business_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.add_column('transaction_audit', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.add_column('transaction_audit', sa.Column('business_id', sa.String(length=255), nullable=True))
    op.add_column('transaction_audit', sa.Column('actor_user_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_transaction_audit_actor_user_id'), 'transaction_audit', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_transaction_audit_business_id'), 'transaction_audit', ['business_id'], unique=False)
    op.create_index(op.f('ix_transaction_audit_tenant_id'), 'transaction_audit', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_audit_tenant_id'), table_name='transaction_audit')
    op.drop_index(op.f('ix_transaction_audit_business_id'), table_name='transaction_audit')
    op.drop_index(op.f('ix_transaction_audit_actor_user_id'), table_name='transaction_audit')
    op.drop_column('transaction_audit', 'actor_user_id')
    op.drop_column('transaction_audit', 'business_id')
    op.drop_column('transaction_audit', 'tenant_id')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_business_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_column('audit_logs', 'actor_user_id')
    op.drop_column('audit_logs', 'business_id')
    op.drop_column('audit_logs', 'tenant_id')
    # ### end Alembic commands ###
