"""Make Phone Unqiue

Revision ID: 327c9c632d86
Revises: 94df2aee584f
Create Date: 2026-03-13 15:04:49.692577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '327c9c632d86'
down_revision: Union[str, Sequence[str], None] = '94df2aee584f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'participants', ['phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'participants', type_='unique')
    # ### end Alembic commands ###
