"""Metadata Addition to Raw Messages

Revision ID: 55d454f85b4e
Revises: 079341ba1d7d
Create Date: 2026-03-19 14:03:46.299180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '55d454f85b4e'
down_revision: Union[str, Sequence[str], None] = '079341ba1d7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_messages', sa.Column('parsing_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_messages', 'parsing_meta')
    # ### end Alembic commands ###
