"""Added tenant_id

Revision ID: 94df2aee584f
Revises: d12994f6f22a
Create Date: 2026-03-09 16:05:32.489247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94df2aee584f'
down_revision: Union[str, Sequence[str], None] = 'd12994f6f22a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_groups_tenant_id'), 'groups', ['tenant_id'], unique=False)
    op.add_column('participants', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_participants_tenant_id'), 'participants', ['tenant_id'], unique=False)
    op.add_column('raw_messages', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_raw_messages_tenant_id'), 'raw_messages', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_messages_tenant_id'), table_name='raw_messages')
    op.drop_column('raw_messages', 'tenant_id')
    op.drop_index(op.f('ix_participants_tenant_id'), table_name='participants')
    op.drop_column('participants', 'tenant_id')
    op.drop_index(op.f('ix_groups_tenant_id'), table_name='groups')
    op.drop_column('groups', 'tenant_id')
    # ### end Alembic commands ###
