"""Bank account and audit logs added

Revision ID: d12994f6f22a
Revises: f44cc51f0a95
Create Date: 2026-03-09 15:24:56.427869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd12994f6f22a'
down_revision: Union[str, Sequence[str], None] = 'f44cc51f0a95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.Enum('CREATE', 'UPDATE', 'DELETE', name='audit_event_type_enum'), nullable=False),
    sa.Column('actor_type', sa.Enum('SYSTEM', 'USER', 'WEBHOOK', name='audit_actor_type_enum'), nullable=False),
    sa.Column('actor_identifier', sa.String(length=255), nullable=True),
    sa.Column('old_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('action_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action_timestamp'), 'audit_logs', ['action_timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_identifier'), 'audit_logs', ['actor_identifier'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_table('bank_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('transaction_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('reference_identifier', sa.String(length=255), nullable=False),
    sa.Column('operator_identifier', sa.String(length=100), nullable=True),
    sa.Column('operator_name', sa.String(length=255), nullable=True),
    sa.Column('resulting_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'reference_identifier', name='uq_tenant_bank_reference')
    )
    op.create_index(op.f('ix_bank_accounts_created_at'), 'bank_accounts', ['created_at'], unique=False)
    op.create_index(op.f('ix_bank_accounts_reference_identifier'), 'bank_accounts', ['reference_identifier'], unique=False)
    op.create_index(op.f('ix_bank_accounts_tenant_id'), 'bank_accounts', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_bank_accounts_transaction_date'), 'bank_accounts', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_bank_accounts_updated_at'), 'bank_accounts', ['updated_at'], unique=False)
    op.create_index(op.f('ix_groups_created_at'), 'groups', ['created_at'], unique=False)
    op.create_index(op.f('ix_groups_updated_at'), 'groups', ['updated_at'], unique=False)
    op.create_index(op.f('ix_participants_created_at'), 'participants', ['created_at'], unique=False)
    op.create_index(op.f('ix_participants_updated_at'), 'participants', ['updated_at'], unique=False)
    op.create_index(op.f('ix_raw_messages_created_at'), 'raw_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_raw_messages_updated_at'), 'raw_messages', ['updated_at'], unique=False)
    op.add_column('transactions', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('parsing_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_transactions_created_at'), 'transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_transactions_tenant_id'), 'transactions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_transactions_updated_at'), 'transactions', ['updated_at'], unique=False)
    op.create_unique_constraint('uq_transaction_raw_message', 'transactions', ['raw_message_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_transaction_raw_message', 'transactions', type_='unique')
    op.drop_index(op.f('ix_transactions_updated_at'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_tenant_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_created_at'), table_name='transactions')
    op.drop_column('transactions', 'parsing_meta')
    op.drop_column('transactions', 'tenant_id')
    op.drop_index(op.f('ix_raw_messages_updated_at'), table_name='raw_messages')
    op.drop_index(op.f('ix_raw_messages_created_at'), table_name='raw_messages')
    op.drop_index(op.f('ix_participants_updated_at'), table_name='participants')
    op.drop_index(op.f('ix_participants_created_at'), table_name='participants')
    op.drop_index(op.f('ix_groups_updated_at'), table_name='groups')
    op.drop_index(op.f('ix_groups_created_at'), table_name='groups')
    op.drop_index(op.f('ix_bank_accounts_updated_at'), table_name='bank_accounts')
    op.drop_index(op.f('ix_bank_accounts_transaction_date'), table_name='bank_accounts')
    op.drop_index(op.f('ix_bank_accounts_tenant_id'), table_name='bank_accounts')
    op.drop_index(op.f('ix_bank_accounts_reference_identifier'), table_name='bank_accounts')
    op.drop_index(op.f('ix_bank_accounts_created_at'), table_name='bank_accounts')
    op.drop_table('bank_accounts')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_identifier'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action_timestamp'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
