"""add_auth0_users_and_tenant_metrics

Revision ID: dbd74f17bcf3
Revises: yyy_enforce_tenant_constraints
Create Date: 2026-06-10 21:58:03.836305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbd74f17bcf3'
down_revision: Union[str, Sequence[str], None] = 'yyy_enforce_tenant_constraints'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('auth0_user_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_auth0_user_id'), 'users', ['auth0_user_id'], unique=True)
    op.create_index(op.f('ix_users_business_id'), 'users', ['business_id'], unique=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_updated_at'), 'users', ['updated_at'], unique=False)
    op.add_column('businesses', sa.Column('onboarding_completed', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('businesses', sa.Column('created_via', sa.String(), server_default='auth0_auto_onboard', nullable=False))
    op.add_column('businesses', sa.Column('onboarded_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_businesses_created_at'), 'businesses', ['created_at'], unique=False)
    op.create_index(op.f('ix_businesses_meta_phone_number_id'), 'businesses', ['meta_phone_number_id'], unique=False)
    op.create_index(op.f('ix_businesses_updated_at'), 'businesses', ['updated_at'], unique=False)
    op.alter_column('groups', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('participants', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('raw_messages', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transactions', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('raw_messages', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('participants', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('groups', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_businesses_updated_at'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_meta_phone_number_id'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_created_at'), table_name='businesses')
    op.drop_column('businesses', 'onboarded_at')
    op.drop_column('businesses', 'created_via')
    op.drop_column('businesses', 'onboarding_completed')
    op.drop_index(op.f('ix_users_updated_at'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index(op.f('ix_users_business_id'), table_name='users')
    op.drop_index(op.f('ix_users_auth0_user_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
