"""Added Indices

Revision ID: f44cc51f0a95
Revises: a64ffe6719ac
Create Date: 2026-03-08 18:19:41.305645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f44cc51f0a95'
down_revision: Union[str, Sequence[str], None] = 'a64ffe6719ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('raw_messages_message_id_key'), 'raw_messages', type_='unique')
    op.create_index(op.f('ix_raw_messages_group_id'), 'raw_messages', ['group_id'], unique=False)
    op.create_index(op.f('ix_raw_messages_message_id'), 'raw_messages', ['message_id'], unique=True)
    op.create_index(op.f('ix_raw_messages_received_at'), 'raw_messages', ['received_at'], unique=False)
    op.create_index(op.f('ix_raw_messages_sender_id'), 'raw_messages', ['sender_id'], unique=False)
    op.drop_column('raw_messages', 'media_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_messages', sa.Column('media_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_raw_messages_sender_id'), table_name='raw_messages')
    op.drop_index(op.f('ix_raw_messages_received_at'), table_name='raw_messages')
    op.drop_index(op.f('ix_raw_messages_message_id'), table_name='raw_messages')
    op.drop_index(op.f('ix_raw_messages_group_id'), table_name='raw_messages')
    op.create_unique_constraint(op.f('raw_messages_message_id_key'), 'raw_messages', ['message_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
